### ISSUE TITLE
Проверка 1

### ISSUE THREAD

**Issue by KseeBMSTU** [themilchenko/LW2.5-Vector_vol.1#1]
- [x] 1. Конструктор по умолчанию не выделяет память. А куда будут ссылаться итераторы?
- [x] 2. Зачем вам 2 раза копировать в reserve?
- [x] 3. Зачем вам в insert и erase копировать во временный массив то, что будете сдвигать?
- [x] 4. Местами явно не учитывается "фантомный" элемент для конечного итератора
- [x] 5. Зачем 2 раза выделять память в resize?
- [x] 6. Отсутствует pop_back
- [x] 7. Добавить в демонстрацию работу с алгоритмами STL

**Comment by themilchenko** [comment]
Исправил
